import { Injectable, signal, computed, inject, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

export type SupportedLanguage = 'vi' | 'en';

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  vi: {
    // Header & Navigation
    'header.logo_tagline': 'Khu vườn Tĩnh Lặng',
    'header.account': 'Tài khoản',
    'header.profile': '👤 Hồ sơ cá nhân',
    'header.change_password': '🔐 Đổi mật khẩu',
    'header.logout': '🚪 Đăng xuất',
    'nav.all_todos': 'Tất cả công việc',
    'nav.all_tasks': 'Tất cả công việc',
    'nav.today': 'Hôm nay',
    'nav.upcoming': 'Sắp tới',
    'nav.categories': 'Khu vườn Danh mục',
    'nav.profile': 'Hồ sơ cá nhân',
    'nav.change_password': 'Đổi mật khẩu',
    'nav.sidebar_categories': 'Danh mục',
    'nav.add_category_title': 'Thêm danh mục mới',
    'nav.edit_category': '✏️ Sửa danh mục',
    'nav.delete_category': '🗑️ Xóa danh mục',
    'cat.detail_title': 'Chi tiết danh mục',
    'cat.study': 'Học tập',
    'cat.work': 'Công việc',
    'cat.other': 'Khác',

    // Search, Filter & Sort
    'search.placeholder': 'Tìm kiếm công việc...',
    'filter.all_categories': 'Tất cả danh mục',
    'filter.all_statuses': 'Tất cả trạng thái',
    'filter.pending': 'Đang ươm mầm (Chưa xong)',
    'filter.completed': 'Đã nở hoa (Hoàn thành)',
    'filter.hidden': 'Đã ẩn 🙈',
    'filter.trash': 'Thùng rác 🗑️',
    'sort.dueDate': 'Hạn chót gần nhất',
    'sort.priorityDesc': 'Ưu tiên cao nhất',
    'empty.todos': '📭 Chưa có công việc nào. Hãy gieo hạt giống đầu tiên!',

    // Todo Item & Form Dialog
    'todo.add_seed': 'Thêm một hạt giống mới',
    'todo.click_view_tree': 'Nhấn để xem cây công việc chi tiết',
    'todo.restore': 'Khôi phục công việc',
    'todo.hard_delete': 'Xóa vĩnh viễn',
    'todo.edit': 'Chỉnh sửa thông tin công việc',
    'todo.delete': 'Xóa công việc',
    'todo.mark_complete': 'Đánh dấu hoàn thành',
    'todo.create_title': 'Gieo hạt giống mới',
    'todo.edit_title': 'Chỉnh sửa hạt giống',
    'todo.label_title': 'Tiêu đề hạt giống *',
    'todo.placeholder_title': 'Nhập tên công việc bạn muốn thực hiện...',
    'todo.label_desc': 'Mô tả chi tiết',
    'todo.placeholder_desc': 'Ghi chú thêm về công việc này...',
    'todo.label_priority': 'Độ ưu tiên',
    'todo.priority_low': '🍃 Thấp',
    'todo.priority_medium': '🌿 Trung bình',
    'todo.priority_high': '🔥 Cao',
    'todo.label_category': 'Danh mục',
    'todo.label_due_date': 'Hạn chót *',
    'todo.is_completed_label': 'Đã nở hoa (Hoàn thành)',
    'todo.btn_pluck': '🗑️ Nhổ bỏ hạt giống',
    'todo.btn_cancel': 'Hủy bỏ',
    'todo.btn_plant': 'Gieo hạt ngay',
    'todo.btn_save_changes': 'Lưu thay đổi',

    // Todo Tree View
    'tree.back_list': 'Danh sách',
    'tree.back_list_title': 'Quay lại danh sách',
    'tree.due_date': '🕒 Hạn chót: ',
    'tree.general_task': 'Công việc chung',
    'tree.toggle_complete_tree': 'Đánh dấu hoàn thành toàn bộ cây',
    'tree.tree_completed': '✓ Cây đã trọn vẹn',
    'tree.tree_sprouting': '🌱 Đang nuôi dưỡng',
    'tree.delete_tree_title': 'Xóa toàn bộ cây công việc này',
    'tree.empty_forest': '🍃 Vườn lá đang chờ chồi non! Hãy nhập nhánh lá mới ở dưới gốc cây để nuôi dưỡng công việc này.',
    'tree.placeholder_add_leaf': 'Thêm một lá cây mới...',
    'tree.title_sow_leaf': 'Gieo lá mới',
    'tree.confirm_delete_tree': 'Bạn có chắc chắn muốn xóa toàn bộ cây công việc này?',
    'tree.confirm_delete_leaf': 'Bạn có muốn lặt nhánh lá công việc con này không?',

    // Category Garden Dashboard & Form
    'cat.garden_title': 'Khu Vườn Danh Mục',
    'cat.garden_subtitle': 'Quản lý và quy hoạch các luống hoa tĩnh lặng trong toàn bộ khu vườn của bạn',
    'cat.add_flowerbed': '+ Thêm luống hoa mới',
    'cat.total_categories': '📁 Tổng số danh mục',
    'cat.total_seeds': '🌱 Tổng hạt giống',
    'cat.total_bloomed': '🌸 Hoa đã nở',
    'cat.overall_progress': '📈 Tiến độ toàn vườn',
    'cat.unit_beds': 'luống',
    'cat.unit_tasks': 'việc',
    'cat.empty_title': 'Khu vườn đang trống',
    'cat.empty_desc': 'Bạn chưa gieo luống danh mục nào. Hãy tạo danh mục đầu tiên để phân loại hạt giống công việc nhé!',
    'cat.create_first': '+ Tạo danh mục đầu tiên',
    'cat.edit_tooltip': 'Chỉnh sửa danh mục',
    'cat.delete_tooltip': 'Xóa danh mục',
    'cat.seeds_count': 'hạt giống',
    'cat.bloomed_count': 'hoa nở',
    'cat.completion_rate': 'Độ hoàn thiện',
    'cat.add_task': '+ Gieo thêm việc',
    'cat.enter_garden': 'Vào khu vườn ›',
    'cat.confirm_delete_title': 'Xác nhận nhổ bỏ danh mục',
    'cat.confirm_delete_msg_prefix': 'Bạn có chắc chắn muốn nhổ bỏ danh mục "',
    'cat.confirm_delete_msg_suffix': '" không? Toàn bộ hạt giống/công việc bên trong sẽ được tự động chuyển giao an toàn sang danh mục "Khác" để không bị mất mát dữ liệu.',
    'cat.form_create_title': 'Tạo danh mục mới',
    'cat.form_edit_title': 'Chỉnh sửa danh mục',
    'cat.form_label_name': 'Tên danh mục *',
    'cat.form_placeholder_name': 'Ví dụ: Học tập, Công việc...',
    'cat.form_label_color': 'Màu sắc chủ đạo (Zen Color)',
    'cat.form_btn_delete': '🗑️ Xóa danh mục',
    'cat.form_btn_update': 'Cập nhật',
    'cat.form_btn_create': 'Tạo mới',

    // User Profile
    'profile.main_title': '👤 Hồ sơ & Cài đặt cá nhân',
    'profile.loading': 'Đang tải thông tin cá nhân...',
    'profile.change_avatar': '📸 Đổi ảnh đại diện',
    'profile.use_default_avatar': '🗑️ Dùng ảnh mặc định',
    'profile.section_identity': '🌿 Thông tin định danh cơ bản',
    'profile.section_identity_desc': 'Đây là thông tin công khai và định danh hiển thị trên toàn hệ thống.',
    'profile.label_username': 'Tên đăng nhập (Username)',
    'profile.placeholder_username': 'Nhập tên đăng nhập (VD: quocbao_99)...',
    'profile.label_email': 'Email đăng nhập',
    'profile.help_email': '💡 Email đăng nhập được khóa bảo mật. Vui lòng liên hệ quản trị viên nếu bạn cần đổi email.',
    'profile.label_bio': 'Dòng trạng thái / Mục tiêu (Bio & Status)',
    'profile.placeholder_bio': 'Chia sẻ cảm hứng hoặc mục tiêu hiện tại của bạn...',
    'profile.section_preferences': '⚙️ Tùy chọn hệ thống (Preferences)',
    'profile.section_pref_desc': 'Các cài đặt ảnh hưởng trực tiếp đến trải nghiệm cá nhân hóa và thông báo của bạn.',
    'profile.label_timezone': 'Múi giờ (Timezone)',
    'profile.help_timezone': '⏰ Múi giờ chính xác giúp hệ thống gửi thông báo nhắc việc và tính hạn chót (due date) chuẩn xác nhất.',
    'profile.label_theme': 'Chế độ hiển thị (Theme)',
    'profile.theme_light': 'Sáng (Light)',
    'profile.theme_dark': 'Tối (Dark)',
    'profile.theme_system': 'Hệ thống',
    'profile.label_language': 'Ngôn ngữ giao diện (Language)',
    'profile.label_first_day': 'Ngày bắt đầu của tuần (First Day of Week)',
    'profile.day_monday': 'Thứ Hai (Monday)',
    'profile.day_monday_sub': 'Chuẩn lịch công việc ISO',
    'profile.day_sunday': 'Chủ Nhật (Sunday)',
    'profile.day_sunday_sub': 'Chuẩn lịch Mỹ / Nhật Bản',
    'profile.btn_submit': '💾 Cập nhật thông tin & cài đặt',
    'profile.btn_submitting': 'Đang lưu các thay đổi...',
    'profile.title': 'Hồ sơ cá nhân',
    'profile.language': 'Ngôn ngữ',
    'profile.theme': 'Giao diện',
    'profile.save': 'Lưu thay đổi',
    'profile.saving': 'Đang lưu...',

    // Auth
    'auth.login_title': 'Đăng nhập',
    'auth.username_or_email': 'Tên đăng nhập hoặc Email',
    'auth.placeholder_username_or_email': 'Nhập tên đăng nhập hoặc email....',
    'auth.password': 'Mật khẩu',
    'auth.placeholder_password': 'Nhập mật khẩu....',
    'auth.btn_login': '🌱 Đăng nhập',
    'auth.processing': 'Đang xử lý...',
    'auth.forget_password': 'Quên mật khẩu?',
    'auth.no_account': 'Chưa có tài khoản?',
    'auth.register_now': 'Đăng ký',
    'auth.register_title': 'Đăng ký tài khoản',
    'auth.btn_register': '🌱 Tạo tài khoản mới',
    'auth.has_account': 'Đã có tài khoản?',
    'auth.login_now': 'Đăng nhập ngay',

    // General Dialogs & Buttons
    'dialog.confirm_delete': 'Bạn có chắc muốn xóa công việc này?',
    'btn.cancel': 'Hủy',
    'btn.confirm': 'Xác nhận',
    'btn.close': 'Đóng',
    'lang.vi': 'Tiếng Việt 🇻🇳',
    'lang.en': 'English 🇬🇧'
  },
  en: {
    // Header & Navigation
    'header.logo_tagline': 'Quiet Garden',
    'header.account': 'Account',
    'header.profile': '👤 User Profile',
    'header.change_password': '🔐 Change Password',
    'header.logout': '🚪 Logout',
    'nav.all_todos': 'All Tasks',
    'nav.all_tasks': 'All Tasks',
    'nav.today': 'Today',
    'nav.upcoming': 'Upcoming',
    'nav.categories': 'Category Garden',
    'nav.profile': 'User Profile',
    'nav.change_password': 'Change Password',
    'nav.sidebar_categories': 'Categories',
    'nav.add_category_title': 'Add new category',
    'nav.edit_category': '✏️ Edit category',
    'nav.delete_category': '🗑️ Delete category',
    'cat.detail_title': 'Category Details',
    'cat.study': 'Study',
    'cat.work': 'Work',
    'cat.other': 'Other',

    // Search, Filter & Sort
    'search.placeholder': 'Search tasks...',
    'filter.all_categories': 'All Categories',
    'filter.all_statuses': 'All Statuses',
    'filter.pending': 'Sprouting (Pending)',
    'filter.completed': 'Bloomed (Completed)',
    'filter.hidden': 'Hidden 🙈',
    'filter.trash': 'Trash 🗑️',
    'sort.dueDate': 'Nearest Due Date',
    'sort.priorityDesc': 'Highest Priority',
    'empty.todos': '📭 No tasks yet. Plant your first seed!',

    // Todo Item & Form Dialog
    'todo.add_seed': 'Plant a new seed',
    'todo.click_view_tree': 'Click to view task tree details',
    'todo.restore': 'Restore task',
    'todo.hard_delete': 'Delete permanently',
    'todo.edit': 'Edit task details',
    'todo.delete': 'Delete task',
    'todo.mark_complete': 'Mark as complete',
    'todo.create_title': 'Plant New Seed',
    'todo.edit_title': 'Edit Seed',
    'todo.label_title': 'Seed Title *',
    'todo.placeholder_title': 'Enter task title...',
    'todo.label_desc': 'Detailed Description',
    'todo.placeholder_desc': 'Add notes for this task...',
    'todo.label_priority': 'Priority',
    'todo.priority_low': '🍃 Low',
    'todo.priority_medium': '🌿 Medium',
    'todo.priority_high': '🔥 High',
    'todo.label_category': 'Category',
    'todo.label_due_date': 'Due Date *',
    'todo.is_completed_label': 'Bloomed (Completed)',
    'todo.btn_pluck': '🗑️ Pluck seed',
    'todo.btn_cancel': 'Cancel',
    'todo.btn_plant': 'Plant Seed',
    'todo.btn_save_changes': 'Save Changes',

    // Todo Tree View
    'tree.back_list': 'Task List',
    'tree.back_list_title': 'Back to list',
    'tree.due_date': '🕒 Due date: ',
    'tree.general_task': 'General Task',
    'tree.toggle_complete_tree': 'Mark whole tree completed',
    'tree.tree_completed': '✓ Tree completed',
    'tree.tree_sprouting': '🌱 Nurturing',
    'tree.delete_tree_title': 'Delete entire task tree',
    'tree.empty_forest': '🍃 Leaf garden is awaiting sprouts! Add a new leaf below to nurture this task.',
    'tree.placeholder_add_leaf': 'Add a new leaf...',
    'tree.title_sow_leaf': 'Sow new leaf',
    'tree.confirm_delete_tree': 'Are you sure you want to delete this entire task tree?',
    'tree.confirm_delete_leaf': 'Do you want to pluck this subtask leaf?',

    // Category Garden Dashboard & Form
    'cat.garden_title': 'Category Garden',
    'cat.garden_subtitle': 'Manage and organize tranquil flowerbeds across your entire garden',
    'cat.add_flowerbed': '+ Add new flowerbed',
    'cat.total_categories': '📁 Total Categories',
    'cat.total_seeds': '🌱 Total Seeds',
    'cat.total_bloomed': '🌸 Bloomed Flowers',
    'cat.overall_progress': '📈 Overall Progress',
    'cat.unit_beds': 'beds',
    'cat.unit_tasks': 'tasks',
    'cat.empty_title': 'Garden is empty',
    'cat.empty_desc': 'You have not planted any category flowerbed yet. Create your first category to organize your seeds!',
    'cat.create_first': '+ Create first category',
    'cat.edit_tooltip': 'Edit category',
    'cat.delete_tooltip': 'Delete category',
    'cat.seeds_count': 'seeds',
    'cat.bloomed_count': 'bloomed',
    'cat.completion_rate': 'Completion rate',
    'cat.add_task': '+ Plant more tasks',
    'cat.enter_garden': 'Enter garden ›',
    'cat.confirm_delete_title': 'Confirm Category Plucking',
    'cat.confirm_delete_msg_prefix': 'Are you sure you want to pluck category "',
    'cat.confirm_delete_msg_suffix': '"? All contained seeds/tasks will be safely transferred to "Other" category to prevent data loss.',
    'cat.form_create_title': 'Create New Category',
    'cat.form_edit_title': 'Edit Category',
    'cat.form_label_name': 'Category Name *',
    'cat.form_placeholder_name': 'e.g. Learning, Work...',
    'cat.form_label_color': 'Primary Zen Color',
    'cat.form_btn_delete': '🗑️ Delete Category',
    'cat.form_btn_update': 'Update',
    'cat.form_btn_create': 'Create',

    // User Profile
    'profile.main_title': '👤 Profile & Personal Settings',
    'profile.loading': 'Loading personal profile...',
    'profile.change_avatar': '📸 Change Avatar',
    'profile.use_default_avatar': '🗑️ Use Default Avatar',
    'profile.section_identity': '🌿 Basic Identity Info',
    'profile.section_identity_desc': 'This public identity information is displayed across the system.',
    'profile.label_username': 'Username',
    'profile.placeholder_username': 'Enter username (e.g. quocbao_99)...',
    'profile.label_email': 'Login Email',
    'profile.help_email': '💡 Login email is locked for security. Contact admin if you need to change email.',
    'profile.label_bio': 'Bio & Personal Status',
    'profile.placeholder_bio': 'Share your inspiration or personal goal...',
    'profile.section_preferences': '⚙️ System Preferences',
    'profile.section_pref_desc': 'Settings that directly impact your personalized experience and notifications.',
    'profile.label_timezone': 'Timezone',
    'profile.help_timezone': '⏰ Accurate timezone helps send task reminders and calculate due dates precisely.',
    'profile.label_theme': 'Display Theme',
    'profile.theme_light': 'Light',
    'profile.theme_dark': 'Dark',
    'profile.theme_system': 'System',
    'profile.label_language': 'Interface Language',
    'profile.label_first_day': 'First Day of Week',
    'profile.day_monday': 'Monday',
    'profile.day_monday_sub': 'ISO work calendar standard',
    'profile.day_sunday': 'Sunday',
    'profile.day_sunday_sub': 'US / Japan calendar standard',
    'profile.btn_submit': '💾 Update Profile & Settings',
    'profile.btn_submitting': 'Saving changes...',
    'profile.title': 'User Profile',
    'profile.language': 'Language',
    'profile.theme': 'Theme',
    'profile.save': 'Save Changes',
    'profile.saving': 'Saving...',

    // Auth
    'auth.login_title': 'Log In',
    'auth.username_or_email': 'Username or Email',
    'auth.placeholder_username_or_email': 'Enter username or email...',
    'auth.password': 'Password',
    'auth.placeholder_password': 'Enter password...',
    'auth.btn_login': '🌱 Log In',
    'auth.processing': 'Processing...',
    'auth.forget_password': 'Forgot password?',
    'auth.no_account': 'Don\'t have an account?',
    'auth.register_now': 'Register',
    'auth.register_title': 'Create Account',
    'auth.btn_register': '🌱 Create New Account',
    'auth.has_account': 'Already have an account?',
    'auth.login_now': 'Log in now',

    // General Dialogs & Buttons
    'dialog.confirm_delete': 'Are you sure you want to delete this task?',
    'btn.cancel': 'Cancel',
    'btn.confirm': 'Confirm',
    'btn.close': 'Close',
    'lang.vi': 'Tiếng Việt 🇻🇳',
    'lang.en': 'English 🇬🇧'
  }
};

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private platformId = inject(PLATFORM_ID);
  currentLang = signal<SupportedLanguage>('vi');

  constructor() {
    if (isPlatformBrowser(this.platformId)) {
      const savedLang = localStorage.getItem('app_language') as SupportedLanguage;
      if (savedLang && (savedLang === 'vi' || savedLang === 'en')) {
        this.currentLang.set(savedLang);
      }
    }
  }

  setLanguage(lang: SupportedLanguage) {
    if (lang !== 'vi' && lang !== 'en') return;
    this.currentLang.set(lang);
    if (isPlatformBrowser(this.platformId)) {
      localStorage.setItem('app_language', lang);
    }
  }

  translate(key: string): string {
    const lang = this.currentLang();
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS['vi']?.[key] || key;
  }
}
